# BLOODY-F4LCON default configuration

timeout_ms = 5000
max_concurrent_requests = 5
cache_ttl_seconds = 600

[[providers]]
name = "github"
enabled = true
base_url = "https://github.com/{username}"

[[providers]]
name = "reddit"
enabled = true
base_url = "https://www.reddit.com/user/{username}"

[[providers]]
name = "steam"
enabled = true
base_url = "https://steamcommunity.com/id/{username}"

[[providers]]
name = "twitter"
enabled = true
base_url = "https://twitter.com/{username}"

[[providers]]
name = "psnprofiles"
enabled = true
base_url = "https://psnprofiles.com/{username}"
